<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ConectaAtende.Communication\ConectaAtende.Communication.csproj" />
		<ProjectReference Include="..\ConectaAtende.Domain\ConectaAtende.Domain.csproj" />
		<ProjectReference Include="..\ConectaAtende.Infrastructure\ConectaAtende.Infrastructure.csproj" />
	</ItemGroup>

</Project>